export const DesktopImgData = [
  { id: 1, url: "/assets/courses/1.webp" },
  { id: 2, url: "/assets/courses/2.webp" },
  { id: 3, url: "/assets/courses/3.webp" },
  { id: 4, url: "/assets/courses/4.webp" },
  { id: 5, url: "/assets/courses/5.webp" },
  { id: 6, url: "/assets/courses/6.webp" },
  { id: 7, url: "/assets/courses/7.webp" },
  { id: 8, url: "/assets/courses/8.webp" },
  { id: 9, url: "/assets/courses/9.webp" },
  { id: 10, url: "/assets/courses/10.webp" },
  { id: 11, url: "/assets/courses/11.webp" },
  { id: 12, url: "/assets/courses/12.webp" },
  { id: 13, url: "/assets/courses/13.webp" },
  { id: 14, url: "/assets/courses/14.webp" },
  { id: 15, url: "/assets/courses/15.webp" },
  { id: 16, url: "/assets/courses/16.webp" },
  { id: 17, url: "/assets/courses/17.webp" },
  { id: 18, url: "/assets/courses/18.webp" },
  { id: 19, url: "/assets/courses/19.webp" },
  { id: 20, url: "/assets/courses/20.webp" },
  { id: 21, url: "/assets/courses/21.webp" },
  { id: 22, url: "/assets/courses/22.webp" },
  { id: 23, url: "/assets/courses/23.webp" },
  { id: 24, url: "/assets/courses/24.webp" },
  { id: 25, url: "/assets/courses/25.webp" },
  { id: 26, url: "/assets/courses/26.webp" },
];

export const AudioData = [
  { id: 1, url: "/assets/audios/1.m4a" },
  { id: 2, url: "/assets/audios/2.m4a" },
  { id: 3, url: "/assets/audios/3.m4a" },
  { id: 4, url: "/assets/audios/4.m4a" },
  { id: 5, url: "/assets/audios/5.m4a" },
  { id: 6, url: "/assets/audios/6.m4a" },
  { id: 7, url: "/assets/audios/7.m4a" },
  { id: 8, url: "/assets/audios/8.m4a" },
  { id: 9, url: "/assets/audios/9.m4a" },
  { id: 10, url: "/assets/audios/10.m4a" },
  { id: 11, url: "/assets/audios/11.m4a" },
  { id: 12, url: "/assets/audios/12.m4a" },
  { id: 13, url: "/assets/audios/13.m4a" },
  { id: 14, url: "/assets/audios/14.m4a" },
  { id: 15, url: "/assets/audios/15.m4a" },
  { id: 16, url: "/assets/audios/16.m4a" },
  { id: 17, url: "/assets/audios/17.m4a" },
  { id: 18, url: "/assets/audios/18.m4a" },
  { id: 19, url: "/assets/audios/19.m4a" },
  { id: 20, url: "/assets/audios/20.m4a" },
  { id: 21, url: "/assets/audios/21.m4a" },
  { id: 22, url: "/assets/audios/22.m4a" },
  { id: 23, url: "/assets/audios/23.m4a" },
  { id: 24, url: "/assets/audios/24.m4a" },
  { id: 25, url: "/assets/audios/25.m4a" },
  { id: 26, url: "/assets/audios/26.m4a" },
];


export const MobileImgData = [
  { id: 1, url: "/assets/courses/1-mobile.webp" },
  { id: 2, url: "/assets/courses/2-mobile.webp" },
  { id: 3, url: "/assets/courses/3-mobile.webp" },
  { id: 4, url: "/assets/courses/4-mobile.webp" },
  { id: 5, url: "/assets/courses/5-mobile.webp" },
  { id: 6, url: "/assets/courses/6-mobile.webp" },
  { id: 7, url: "/assets/courses/7-mobile.webp" },
  { id: 8, url: "/assets/courses/8-mobile.webp" },
  { id: 9, url: "/assets/courses/9-mobile.webp" },
  { id: 10, url: "/assets/courses/10-mobile.webp" },
  { id: 11, url: "/assets/courses/11-mobile.webp" },
  { id: 12, url: "/assets/courses/12-mobile.webp" },
  { id: 13, url: "/assets/courses/13-mobile.webp" },
  { id: 14, url: "/assets/courses/14-mobile.webp" },
  { id: 15, url: "/assets/courses/15-mobile.webp" },
  { id: 16, url: "/assets/courses/16-mobile.webp" },
  { id: 17, url: "/assets/courses/17-mobile.webp" },
  { id: 18, url: "/assets/courses/18-mobile.webp" },
  { id: 19, url: "/assets/courses/19-mobile.webp" },
  { id: 20, url: "/assets/courses/20-mobile.webp" },
  { id: 21, url: "/assets/courses/21-mobile.webp" },
  { id: 22, url: "/assets/courses/22-mobile.webp" },
  { id: 23, url: "/assets/courses/23-mobile.webp" },
  { id: 24, url: "/assets/courses/24-mobile.webp" },
  { id: 25, url: "/assets/courses/25-mobile.webp" },
  { id: 26, url: "/assets/courses/26-mobile.webp" },
  { id: 27, url: "/assets/courses/27-mobile.webp" },
  { id: 28, url: "/assets/courses/28-mobile.webp" },
  { id: 29, url: "/assets/courses/29-mobile.webp" },
];




export const AudioDataMobile = [
  { id: 1, url: "/assets/audios/1.m4a" },
  { id: 2, url: "/assets/audios/2.m4a" },
  { id: 3, url: "/assets/audios/3.m4a" },
  { id: 4, url: "/assets/audios/4.m4a" },
  { id: 5, url: "/assets/audios/5.m4a" },
  { id: 6, url: "/assets/audios/6.m4a" },
  { id: 7, url: "/assets/audios/7.m4a" },
  { id: 8, url: "/assets/audios/8.m4a" },
  { id: 9, url: "/assets/audios/8.m4a" },
  { id: 10, url: "/assets/audios/9.m4a" },
  { id: 11, url: "/assets/audios/10.m4a" },
  { id: 12, url: "/assets/audios/10.m4a" },
  { id: 13, url: "/assets/audios/11.m4a" },
  { id: 14, url: "/assets/audios/12.m4a" },
  { id: 15, url: "/assets/audios/13.m4a" },
  { id: 16, url: "/assets/audios/14.m4a" },
  { id: 17, url: "/assets/audios/15.m4a" },
  { id: 18, url: "/assets/audios/16.m4a" },
  { id: 19, url: "/assets/audios/17.m4a" },
  { id: 20, url: "/assets/audios/18.m4a" },
  { id: 21, url: "/assets/audios/19.m4a" },
  { id: 22, url: "/assets/audios/20.m4a" },
  { id: 23, url: "/assets/audios/21.m4a" },
  { id: 24, url: "/assets/audios/22.m4a" },
  { id: 25, url: "/assets/audios/22.m4a" },
  { id: 26, url: "/assets/audios/23.m4a" },
  { id: 27, url: "/assets/audios/24.m4a" },
  { id: 28, url: "/assets/audios/25.m4a" },
  { id: 29, url: "/assets/audios/26.m4a" },
];